// <auto-generated />
namespace Chat.FE.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class IdentityInitializer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdentityInitializer));
        
        string IMigrationMetadata.Id
        {
            get { return "201606231946041_IdentityInitializer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
